<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1" />
    <PackageReference Include="MongoDB.EntityFrameworkCore" Version="8.2.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\shared\RestaurantManagement.Shared\RestaurantManagement.Shared.csproj" />
    <ProjectReference Include="..\..\..\services\bus\RestaurantManagement.Bus\RestaurantManagement.Bus.csproj" />
  </ItemGroup>

</Project>
